embeddings {
  tensor_name: "ss_id:00780"
  metadata_path: "00780/ss_id/metadata.tsv"
  tensor_path: "00780/ss_id/tensors.tsv"
}
embeddings {
  tensor_name: "month:00780"
  metadata_path: "00780/month/metadata.tsv"
  tensor_path: "00780/month/tensors.tsv"
}
embeddings {
  tensor_name: "day_of_week:00780"
  metadata_path: "00780/day_of_week/metadata.tsv"
  tensor_path: "00780/day_of_week/tensors.tsv"
}
embeddings {
  tensor_name: "day_hour:00780"
  metadata_path: "00780/day_hour/metadata.tsv"
  tensor_path: "00780/day_hour/tensors.tsv"
}
